spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB  # 파일 크기 제한 설정
        max-request-size: 10MB  # 요청 크기 제한 설정

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true


  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${K_CLIENT_ID}
            client-secret: ${K_CLIENT_SECRET}
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_image, account_email
            redirect-uri: http://fitfolio1.s3-website.ap-northeast-2.amazonaws.com/oauthloading

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

logging:
  level:
    p6spy: info
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false